sudo: required

dist: trusty

language: node_js

node_js:
  - 6

services:
  - docker

before_install:
  - docker build -t solar/sunrise -f Dockerfile.dev .

script:
  - docker run solar/sunrise npm test -- --coverage

branches:
  only:
    - dev