sudo: required

dist: trusty

language: node_js

node_js:
  - 6

services:
  - docker

before_install:
  - docker build -t solar/sunrise .

script:
  - docker run solar/sunrise npm test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "solar"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-135780901986"
  bucket_path: "solar"
  on:
    branch: dev
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

branches:
  only:
    - dev