sudo: required

dist: trusty

language: node_js

node_js:
  - 6

services:
  - docker build -t solar/sunrise .

script:
  - docker run solar/sunrise npm test -- --coverage

branches:
  only:
    - dev